project:
  type: website
  output-dir: docs

website:
  title: "Spotify Listening Dashboard"
  description: "Personal Spotify listening analytics and insights"
  navbar:
    left:
      - href: index.html
        text: Home
      - href: summary.html
        text: Summary
      - href: artists.html
        text: Artists
    right:
      - icon: github
        href: https://github.com/eivicent/spotifyr-playlists-parser

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    code-fold: true
    code-tools: true
    css: styles.css

execute:
  echo: false
  warning: false
  message: false



